---
chdir: "/var/www/vkino/current"
environment: production
timeout: 30
wait: 30
log: "/var/www/vkino/shared/log/thin.log"
pid: "/tmp/thin.vkino.pid"
max_conns: 1024
max_persistent_conns: 100
require: []
threadpool_size: 20
servers: 2
daemonize: true
socket: "/tmp/vkino.socket"
