development:
  adapter: mysql2
  encoding: utf8
  database: vkino_dev
  pool: 5
  username: root
  password:
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  database: vkino_production
  pool: 5
  username: root
  password:
  host: localhost
